### ISSUE TITLE
I pull new update code and I have Error

### ISSUE THREAD

**Issue by arno608rw** [Decawave/mynewt-dw1000-apps#3]
I pull new update code and I have Error

newt run twr_node 0
![screen shot 2561-11-08 at 10 00 03](https://user-images.githubusercontent.com/3774145/48175088-26e74100-e33d-11e8-830c-a8f43ce1d2a2.png)

newt run twr_tag 0
![screen shot 2561-11-08 at 10 01 07](https://user-images.githubusercontent.com/3774145/48175108-3c5c6b00-e33d-11e8-9235-7616208372ee.png)

**Comment by pkettle** [comment]
Hi Arno,
Thanks for this. This is a new one.
What compiler version are you using?

1. 

Did you do a
`newt update -v `

The recent update was a refactoring of the code base that touched the dependent repos. 

2. 

Can I have you try changing
mynewt-dw1000-apps/repo/mynewt-dw1000-core/hw/drivers/dw1000/syscfg.yml:75

From:
```
 PANID:
        description: >
          Default Pan ID
        value: ((uint16_t){0xdeca})
```

To 

 ```
PANID:
        description: >
          Default Pan ID
        value: ((const uint16_t){0xdeca})
```
